.TH studyflash 1 "17 June 2020" "1.1.3" "studyflash man page"

.SH NAME 
studyflash \- Learn flashcards inside your terminal!

.SH SYNOPSIS
studyflash [\fIOPTION\fI] [\fIFILENAME\fI]

.SH DESCRIPTION
.PP
Studyflash is python application for learning flashcards inside your terminal. 
Best for language learning. 
Supports UTF-8 input so you can learn languages with non-english characters.
.PP
You are able to export / import cards from a CSV file or you can import them directly from Quizlet.
.PP
A staple of flashcards, which you want to learn, is represented as a file.
Configuration considering these cards is stored there aswell.
You can generate such a file with "studyflash new [FILENAME]"
.PP
Read the man page of studyflash-quizlet to for information about downloading flashcards from Quizlet.
.PP
For more information read the 'COMMAND' section of this man page.

.SH COMMANDS

.SS
studyflash new [\fIFILENAME\fR]
.PP
A studyflash file is being created. Now you can use 'edit' or 'add' to add cards.

.SS 
studyflash add [\fIFILENAME\fR]
.PP
User can add flashcards to file.
.PP
NOTE: It is recommended to use 'edit' for adding cards, because you currently cannot fix typos with add.

.SS 
studyflash study [\fIFILENAME\fR]
.PP
Learn your flashcards.
You need to type them correctly.
If you made a typo you can press "c" to count your answer as correct.

.SS
studyflash edit [\fIFILENAME\fR]
.PP
Your editor (default: vi) opens with all your cards in it. 
You can change all the answers/questions of your flashcards. 
.PP
Deleting a card by renaming the answer/question to '###' is also possible.

.SS
studyflash editor [\fIFILENAME\fR] [\fIEDITOR\fR]
.PP
Change your editor from vi to something different. 

.SS
studyflash shuffle [\fIFILENAME\fR]
.PP 
Shuffle your cards automatically after each round.

.SS
studyflash shuffle\-auto [\fIFILENAME\fR]
.PP 
Shuffle your cards automatically after each round.

.SS
studyflash shuffle\-manual [\fIFILENAME\fR]
.PP 
Stop automatic shuffling.

.SS 
studyflash condition [\fIFILENAME\fR]
.PP
You can configure if when a card should no longer appear and should be considered as mastered.
More informations is available when you type the command.

.SS
studyflash reset [\fIFILENAME\fR]
.PP
Resets your statistics, so you can start studying from scratch again.

.SS
studyflash import [\fICSV_FILE\fR] [\fIFILENAME\fR]
.PP
Imports a CSV file.
.PP
When the output (FILENAME) file already exists, the cards are going to be added to the existing ones.

.SS
studyflash export [\fIFILENAME\fR] [\fICSV_FILE\fR] [\fIDELIMITER\fR (optional) ]
.PP
Exports a CSV file
.PP
If no delimiter is specified "\\t" will be used.

.SS 
studyflash reverse [\fIFILENAME\fR]
.PP
Switch answers and solutions of each card

.SH SEE ALSO
studyflash-quizlet(1)
vi(1)
.SH AUTHOR
Alone2 (https://github.com/Alone2/)
