#!/bin/python3

import sys
import json
import csv
from studyFlash import study

class main:
    def __init__(self):
        self.args = sys.argv
        self.studyFlashName = self.args[0].split("/")[-1].split("-csv")[0]

        # Tests if arguments there
        if len(sys.argv) < 3:
            print("needs 2 arguments ( [csv file] [output filename] )")
            print("     -> creates a flashcards file with the name [filename]\n" +
                  "        out of the flashcards from [quizlet link]")
            print("     -> when the file already exists it appends the flashcards\n" +
                  "        to the existing ones")
            return

        arguments = self.args[1:]
        inp = arguments[0]
        out = arguments[1]

        # new file
        study.cardList().new(
            out, errormsg="File is alredy here.\nAppending flashcards to existing ones...")
        # new Card from Csv

        k = 0 
        myCard = None
        for i in [";", "\t", ","]:
            try:
                k += 1
                myCard = self.cardsFromFile(inp,out,i)
                break
            except Exception:
                pass
        if (k <= 0):
            print("Error opening file...")
            return
        myCard.save(out)

        print("Created file from Quizlet.\nStudy: " +
              self.studyFlashName + " study [FILENAME]")

    # returns cards
    def cardsFromFile(self, inp, path, delimiter):
        cards = study.cardList()
        cards.get(path)
        i = 0
        with open(inp) as f:
            reader = csv.reader(f, delimiter=delimiter)
            for row in reader:
                i += 1
                print(row)
                if len(row) <= 1 and i > 1:
                    raise Exception()
                elif len(row) <= 1:
                    continue
                c = study.card(row[0], row[1])
                cards.add_new(c)
        return cards
        



if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        # Save exit comming soon!
        print("\n")
        sys.exit()
